### ISSUE TITLE
Hide the QR Code when any value is changed in Inputs

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/UPI-QR-Code-Generator#6]
To achieve this you can  -

- apply useEffect hook on inputs usestate variable ( when any value is change the useEfffect funciton will trigger )

**Comment by shinobig** [comment]
Where does this happen? you can assign it to me, I can take a look
I think it's easier to validate and render the QR based on the input content, you don't need useEffect for that but I would need to take a look to see what's up

**Comment by PiyushKalyanpy** [comment]
> Where does this happen? you can assign it to me, I can take a look I think it's easier to validate and render the QR based on the input content, you don't need useEffect for that but I would need to take a look to see what's up

Inside the index.js file in pages folder, you can use the useEffect hook which will run only if the input value changes. 
You can use - the `const [formData, setFormData]` formData useState variable as  the useEffect parameter, something like this 
`
useEffect(() => {
}, [formData]); // run only if formData changes and you can set qrCodeValue to empty.
`
